version: '3'
services: 
  unitree_ros2-jetson:
    volumes: 
      - ..:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg
      - /root/.gazebo/models/:/root/.gazebo/models/
      - /var/run/docker.sock:/var/run/docker.sock 
      - $HOME/.Xauthority:/tmp/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority

    cap_add:
      - SYS_PTRACE  
    command: /bin/sh -c "while sleep 1000; do :; done"
 
    build:
      context: .
      dockerfile: Dockerfile.jetson
    image: unitree_ros2:jetson
    container_name: unitree_ros2-jetson
    
    # run `cd .devcontainer/ && docker build . -t ros2-humble-dev:latest -f Dockerfile-humble` 
    # to use the development environment, or you can build it with Dockerfile.
    # Perhaps Unitree will provide a dockerhub image later to save you time compiling.
    privileged: true
    network_mode: "host"

  unitree_ros2-azure:
    volumes:
      - ..:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg
      - /root/.gazebo/models/:/root/.gazebo/models/
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.Xauthority:/tmp/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority

    cap_add:
      - SYS_PTRACE
    command: /bin/sh -c "while sleep 1000; do :; done"

    build:
      context: .
      dockerfile: Dockerfile.azure
    image: unitree_ros2:azure
    container_name: unitree_ros2-azure

    # run `cd .devcontainer/ && docker build . -t ros2-humble-dev:latest -f Dockerfile-humble`
    # to use the development environment, or you can build it with Dockerfile.
    # Perhaps Unitree will provide a dockerhub image later to save you time compiling.
    privileged: true
    network_mode: "host"

